### ISSUE TITLE
vi default_config.py

### ISSUE THREAD

**Issue by eepocket** [glucee/unblockyouku_gateway#1]
# 修改 Shadowsocks 服务器配置
$ vi default_config.py
这一步具体是要修改哪些部分呢？
一键配置提示当前环境ipset不可用啊

**Comment by glucee** [comment]
你使用的是什么系统？需要安装ipset
修改的主要是你的Shadowsocks服务器的设置

**Comment by eepocket** [comment]
感谢回复，我自己捉摸着可能是这么个事，就装上了ipset...现在一件配置算是过去了，但是网络的设置可能是有点问题，我现在还没有搞明白怎么个事。
我的路由器是edgerouter所以怎么能设置gateway还没摸索清楚，现在路由器的地址是192.168.1.1上。我的raspberry Pi按照你文中指导现在都配置好了，IP是192.168.1.8。按照你文中指导是说如果安装安装好后把所有客户端的IP设置都改成192.168.1.8做gateway，8.8.8.8做dns，就可以翻回祖国了是吗？然而我鼓捣了好几天并不行...我把gateway设置成192.168.1.8就不能上网了。
反复试了很多遍不知道问题在哪，我国内的VPS也做好了SS服务器，手机测试没问题，单独用PC测试也没问题，就是这个透明网关有点问题。

再次感谢你抽时间回复

**Comment by glucee** [comment]
事实上，你可以通过命令测试，是否网关是成功的
https://github.com/glucee/unblock_youku_gateway#%E6%A3%80%E6%9F%A5-urlip%E5%9F%9F%E5%90%8D-%E6%98%AF%E5%90%A6%E8%B5%B0%E4%BB%A3%E7%90%86

如果网关OKay，你需要把客户端的gateway修改成网关地址如92.168.1.8，子网掩码255.255.255.0，DNS：8.8.8.8，客户端的IP应该是**另一个地址**如192.168.1.9

**Comment by eepocket** [comment]
如下命令全部测试通过，看上去这个代理是有效的，然而测试过程中我也看过国内SS服务器状态，好像是没有什么连接信息，所以我认为下面这些命令应该是本地的测试，不是实际的与国内通信的测试。
$ sudo python3 unblockgw.py check http://ipservice.163.com/isFromMainland
59.111.19.7 走代理
$ sudo python3 unblockgw.py check https://google.com
216.58.193.78 不走代理
$ sudo python3 unblockgw.py check www.bilibili.com
148.153.45.166 走代理
$ sudo python3 unblockgw.py check 192.168.2.1
192.168.2.1 不走代理

客户端方面我也是按照你写的修改过，但是没有用处，改了以后就什么都上不去了，我怀疑我可能需要在路由器里面设置些什么。现在主要就是卡在这了。。。

**Comment by glucee** [comment]
我看到根据你的输出，上面的域名都是能转化成IP的，感觉网关服务器是什么问题的。

**Comment by jzhengdj** [comment]
同用edgerouter的路过。[参考](https://medium.com/@oliviaqrs/%E5%88%A9%E7%94%A8shadowsocks%E6%89%93%E9%80%A0%E5%B1%80%E5%9F%9F%E7%BD%91%E7%BF%BB%E5%A2%99%E9%80%8F%E6%98%8E%E7%BD%91%E5%85%B3-fb82ccb2f729)

edgerouter那边不需要做设置，需要在raspberry pi上改以下。
1. 修改 /etc/sysctl.conf， 取消注释:
net.ipv4.ip_forward=1
2. 执行命令使其生效
sysctl -p

**Comment by joeylu** [comment]
@glucee 如果按照树莓派的初始环境，@eepocket 的问题会是常见的，@jzhengdj的修改 sysctl.conf是解决方案，不修改的话，你的整个环境最终无法让任何一台客户端连接上，一旦把客户端的gateway设置成树莓派的ip，立马所有网站都上不了的，建议修改下你的“配置”那一块
不过整个方案非常赞，star +1

**Comment by glucee** [comment]
@joeylu @jzhengdj Thanks for your suggestion, already added it in the readme

**Comment by tjbwyk** [comment]
最重要的一步，透明网关需要设置数据包转发的地址：

```
route del default
route add default gw 192.168.0.1 eth0
```
